[workspace]
resolver = "2"

members = ["hook-common", "hook-producer", "hook-consumer", "hook-janitor"]

[workspace.dependencies]
axum = { version = "0.7.1", features = ["http2"] }
chrono = { version = "0.4" }
envconfig = "0.10.0"
eyre = "0.6.9"
futures = { version = "0.3.29" }
http = { version = "0.2" }
http-body-util = "0.1.0"
metrics = "0.21.1"
metrics-exporter-prometheus = "0.12.1"
serde = { version = "1.0" }
serde_derive = { version = "1.0" }
serde_json = { version = "1.0" }
sqlx = { version = "0.7", features = [
  "runtime-tokio",
  "tls-native-tls",
  "postgres",
  "uuid",
  "json",
  "chrono",
] }
thiserror = { version = "1.0" }
tokio = { version = "1.34.0", features = ["full"] }
tower = "0.4.13"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
url = { version = "2.5.0 " }
