services:
    db:
        container_name: db
        image: docker.io/library/postgres:16-alpine
        restart: on-failure
        environment:
            POSTGRES_USER: posthog
            POSTGRES_DB: posthog
            POSTGRES_PASSWORD: posthog
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U posthog']
            interval: 5s
            timeout: 5s
        ports:
            - '15432:5432'
        command: postgres -c max_connections=1000 -c idle_in_transaction_session_timeout=300000

    setup_test_db:
        container_name: setup-test-db
        build:
            context: .
            dockerfile: Dockerfile.migrate
        restart: on-failure
        depends_on:
            db:
                condition: service_healthy
                restart: true
        environment:
            DATABASE_URL: postgres://posthog:posthog@db:5432/test_database

    echo_server:
        image: docker.io/library/caddy:2
        container_name: echo-server
        restart: on-failure
        ports:
            - '18081:8081'
        volumes:
            - ./docker/echo-server/Caddyfile:/etc/caddy/Caddyfile
