name: Build hook-consumer docker image

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

permissions:
  packages: write

jobs:
  build:
    name: build and publish hook-consumer image
    runs-on: buildjet-4vcpu-ubuntu-2204-arm
    steps:

      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/posthog/hook-consumer
          tags: |
            type=ref,event=pr
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push consumer
        id: docker_build_hook_consumer
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: BIN=hook-consumer

      - name: Hook-consumer image digest
        run: echo ${{ steps.docker_build_hook_consumer.outputs.digest }}
